# Generated by Django 4.2.6 on 2023-10-22 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='destinations/images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100)),
                ('program_description', models.TextField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.destination')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition', models.DecimalField(decimal_places=2, max_digits=10)),
                ('housing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.programdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.programdetails')),
            ],
        ),
    ]
