# Generated by Django 4.2.6 on 2023-10-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
