# Generated by Django 4.2.6 on 2023-10-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('how_did_you_hear', models.CharField(max_length=100)),
                ('inquiry', models.TextField()),
                ('passport', models.FileField(blank=True, null=True, upload_to='uploads/passports/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='uploads/cvs/')),
                ('transcript', models.FileField(blank=True, null=True, upload_to='uploads/transcripts/')),
            ],
        ),
    ]
