# Generated by Django 4.2.6 on 2023-10-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
